/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.snake;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.Timer;






/**
 *
 * @author carpraesc
 */
public class Board extends JPanel implements DrawSquareInterface {
    
    /*class MyKeyAdapter extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {
            switch (e.getKeyCode()) {
                case KeyEvent.VK_LEFT:
                    if (timer.isRunning() && canMove(currentRow, currentCol - 1, currentShape)) { //currentCol -1 sirve para comprobar si se puede mover hacia la izquierda
                        currentCol--;
                    }
                    break;
                case KeyEvent.VK_RIGHT:
                    if (timer.isRunning() && canMove(currentRow, currentCol + 1, currentShape)) { //currentCol + 1 sirve para comprobar si se puede mover hacia la derecha
                        currentCol++;
                    }
                    break;
                case KeyEvent.VK_UP:
                    rotate();
                    break;
                case KeyEvent.VK_DOWN:
                    if (timer.isRunning() && canMove(currentRow + 1, currentCol, currentShape)) {
                        currentRow++;
                    }
                    break;
                case KeyEvent.VK_SPACE:
                    
                default:
                    break;
            }
            repaint();
        }
    }*/
    
    public static final int NUM_COLSROWS = 20;
    private int currentRow;
    private int currentCol;
    //private MyKeyAdapter keyAdapter;
    private Snake snake;
    private DrawSquareInterface drawSquareInterface;
    private Timer timer;
    
    public Board() {
        snake = new Snake(this);
    }
    
    
    
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        snake.paint(g);
        Toolkit.getDefaultToolkit().sync();
    }
    
    private int squareWidth() {
        return getWidth() / NUM_COLSROWS;
    }

    private int squareHeight() {
        return getHeight() / NUM_COLSROWS;
    }

    
    public void drawSquare(Graphics g, int row, int col,
            boolean isHead) {
        /*Color colors[] = {new Color(0, 0, 0),
            new Color(204, 102, 102),
            new Color(102, 204, 102), new Color(102, 102, 204),
            new Color(204, 204, 102), new Color(204, 102, 204),
            new Color(102, 204, 204), new Color(218, 170, 0)
        };*/
        int x = col * squareWidth();
        int y = row * squareHeight();
        Color color = isHead ? new Color(204, 102, 102) : new Color (102, 102, 204);
        g.setColor(color);
        g.fillRect(x + 1, y + 1, squareWidth() - 2,
                squareHeight() - 2);
        g.setColor(color.brighter());
        g.drawLine(x, y + squareHeight() - 1, x, y);
        g.drawLine(x, y, x + squareWidth() - 1, y);
        g.setColor(color.darker());
        g.drawLine(x + 1, y + squareHeight() - 1,
                x + squareWidth() - 1, y + squareHeight() - 1);
        g.drawLine(x + squareWidth() - 1,
                y + squareHeight() - 1,
                x + squareWidth() - 1, y + 1);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
